// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ozonmp/rcn_service_api/v1/rcn_service_api.proto

package rcn_service_api

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Template struct {
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Foo                  uint64                 `protobuf:"varint,2,opt,name=foo,proto3" json:"foo,omitempty"`
	Created              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaca51dfdace6973, []int{0}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Template) GetFoo() uint64 {
	if m != nil {
		return m.Foo
	}
	return 0
}

func (m *Template) GetCreated() *timestamppb.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type DescribeTemplateV1Request struct {
	TemplateId           uint64   `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTemplateV1Request) Reset()         { *m = DescribeTemplateV1Request{} }
func (m *DescribeTemplateV1Request) String() string { return proto.CompactTextString(m) }
func (*DescribeTemplateV1Request) ProtoMessage()    {}
func (*DescribeTemplateV1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaca51dfdace6973, []int{1}
}

func (m *DescribeTemplateV1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTemplateV1Request.Unmarshal(m, b)
}
func (m *DescribeTemplateV1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTemplateV1Request.Marshal(b, m, deterministic)
}
func (m *DescribeTemplateV1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTemplateV1Request.Merge(m, src)
}
func (m *DescribeTemplateV1Request) XXX_Size() int {
	return xxx_messageInfo_DescribeTemplateV1Request.Size(m)
}
func (m *DescribeTemplateV1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTemplateV1Request.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTemplateV1Request proto.InternalMessageInfo

func (m *DescribeTemplateV1Request) GetTemplateId() uint64 {
	if m != nil {
		return m.TemplateId
	}
	return 0
}

type DescribeTemplateV1Response struct {
	Value                *Template `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DescribeTemplateV1Response) Reset()         { *m = DescribeTemplateV1Response{} }
func (m *DescribeTemplateV1Response) String() string { return proto.CompactTextString(m) }
func (*DescribeTemplateV1Response) ProtoMessage()    {}
func (*DescribeTemplateV1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaca51dfdace6973, []int{2}
}

func (m *DescribeTemplateV1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTemplateV1Response.Unmarshal(m, b)
}
func (m *DescribeTemplateV1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTemplateV1Response.Marshal(b, m, deterministic)
}
func (m *DescribeTemplateV1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTemplateV1Response.Merge(m, src)
}
func (m *DescribeTemplateV1Response) XXX_Size() int {
	return xxx_messageInfo_DescribeTemplateV1Response.Size(m)
}
func (m *DescribeTemplateV1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTemplateV1Response.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTemplateV1Response proto.InternalMessageInfo

func (m *DescribeTemplateV1Response) GetValue() *Template {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Template)(nil), "ozonmp.rcn_service_api.v1.Template")
	proto.RegisterType((*DescribeTemplateV1Request)(nil), "ozonmp.rcn_service_api.v1.DescribeTemplateV1Request")
	proto.RegisterType((*DescribeTemplateV1Response)(nil), "ozonmp.rcn_service_api.v1.DescribeTemplateV1Response")
}

func init() {
	proto.RegisterFile("ozonmp/rcn_service_api/v1/rcn_service_api.proto", fileDescriptor_aaca51dfdace6973)
}

var fileDescriptor_aaca51dfdace6973 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0x92, 0xf6, 0xb3, 0x32, 0x05, 0x91, 0x01, 0xb1, 0x8d, 0x8a, 0x25, 0xdd, 0x74, 0xd3,
	0x09, 0x8d, 0x75, 0x21, 0xae, 0x2c, 0x16, 0x71, 0x25, 0xc4, 0xa2, 0xe0, 0xa6, 0x4c, 0x92, 0x69,
	0x1c, 0x4c, 0x32, 0x63, 0x66, 0x92, 0x85, 0xe2, 0xc6, 0x57, 0xf0, 0x1d, 0x7c, 0x0e, 0xdf, 0xc1,
	0x57, 0xf0, 0x29, 0x5c, 0x49, 0x7e, 0x06, 0x4a, 0xb4, 0x82, 0xbb, 0x9b, 0x73, 0xee, 0x39, 0x27,
	0xf7, 0xce, 0x05, 0x16, 0x7b, 0x60, 0x71, 0xc4, 0xad, 0xc4, 0x8b, 0xe7, 0x82, 0x24, 0x19, 0xf5,
	0xc8, 0x1c, 0x73, 0x6a, 0x65, 0xa3, 0x3a, 0x84, 0x78, 0xc2, 0x24, 0x83, 0xdd, 0x52, 0x80, 0xea,
	0x6c, 0x36, 0x32, 0xb6, 0x33, 0x1c, 0x52, 0x1f, 0x4b, 0x62, 0xa9, 0xa2, 0xd4, 0x18, 0xbb, 0x01,
	0x63, 0x41, 0x48, 0xac, 0xdc, 0x18, 0xc7, 0x31, 0x93, 0x58, 0x52, 0x16, 0x8b, 0x8a, 0xdd, 0xaf,
	0xd8, 0xe2, 0xcb, 0x4d, 0x17, 0x96, 0xa4, 0x11, 0x11, 0x12, 0x47, 0xbc, 0x6c, 0x30, 0x5d, 0xb0,
	0x3e, 0x23, 0x11, 0x0f, 0xb1, 0x24, 0x70, 0x03, 0xe8, 0xd4, 0xef, 0x68, 0x3d, 0x6d, 0xd0, 0x74,
	0x74, 0xea, 0xc3, 0x4d, 0xd0, 0x58, 0x30, 0xd6, 0xd1, 0x0b, 0x20, 0x2f, 0xe1, 0x18, 0xb4, 0xbc,
	0x84, 0x60, 0x49, 0xfc, 0x4e, 0xa3, 0xa7, 0x0d, 0xda, 0xb6, 0x81, 0xca, 0x00, 0xa4, 0x02, 0xd0,
	0x4c, 0x05, 0x38, 0xaa, 0xd5, 0x9c, 0x82, 0xee, 0x29, 0x11, 0x5e, 0x42, 0x5d, 0xa2, 0xb2, 0xae,
	0x46, 0x0e, 0xb9, 0x4f, 0x89, 0x90, 0x70, 0x00, 0xda, 0xb2, 0x02, 0xe7, 0x2a, 0x7d, 0xd2, 0xfa,
	0x9c, 0x34, 0x6d, 0xbd, 0xf7, 0xcf, 0x01, 0x8a, 0x3b, 0xf7, 0xcd, 0x6b, 0x60, 0xfc, 0x64, 0x23,
	0x38, 0x8b, 0x05, 0x81, 0x47, 0xe0, 0x7f, 0x86, 0xc3, 0x94, 0x14, 0x0e, 0x6d, 0xbb, 0x8f, 0x56,
	0xee, 0x12, 0x29, 0xb5, 0x53, 0x2a, 0xec, 0x37, 0x0d, 0x6c, 0x5d, 0x44, 0x5c, 0xc1, 0x27, 0x9c,
	0x5e, 0x96, 0x02, 0xf8, 0xaa, 0x01, 0xf8, 0x3d, 0x13, 0x8e, 0x7f, 0x31, 0x5f, 0x39, 0xa9, 0x71,
	0xf8, 0x47, 0x55, 0x39, 0x98, 0xd9, 0x7f, 0x7e, 0xff, 0x78, 0xd1, 0xf7, 0xe0, 0x4e, 0x7e, 0x37,
	0x6a, 0x1d, 0xc2, 0x7a, 0x5c, 0xda, 0xda, 0xd3, 0xe4, 0xec, 0x66, 0x1a, 0x50, 0x79, 0x9b, 0xba,
	0xc8, 0x63, 0xd1, 0xd2, 0xdd, 0x0d, 0xab, 0x9c, 0x61, 0x7e, 0x1e, 0xfc, 0x2e, 0xa8, 0x63, 0xc7,
	0xb5, 0x7f, 0x71, 0xd7, 0x8a, 0x87, 0x3c, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x2a, 0x37,
	0xbc, 0xbc, 0x02, 0x00, 0x00,
}
